parameters:
#    info_report.example.class: Info\ReportBundle\Example

services:
#    info_report.example:
#        class: %info_report.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
