info_report:
    resource: "@InfoReportBundle/Resources/config/routing.yml"
    prefix:   /report

info_notification:
    resource: "@InfoNotificationBundle/Resources/config/routing.yml"
    prefix:   /

info_comment:
    resource: "@InfoCommentBundle/Resources/config/routing.yml"
    prefix:   /

info_user:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing.yml"
    prefix:   /

info_complaint:
    resource: "@InfoComplaintBundle/Resources/config/routing.yml"
    prefix:   /

nurix_page:
    resource: "@InfoPageBundle/Resources/config/routing.yml"
    prefix:   /

strokit_core:
    resource: "@StrokitCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

sonata_user_security:
    resource: "@ApplicationSonataUserBundle/Resources/config/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@ApplicationSonataUserBundle/Resources/config/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@ApplicationSonataUserBundle/Resources/config/sonata_change_password_1.xml"
    prefix: /profile

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb

cke_sonata_admin_browse:
    pattern: /admin/sonata/media/media/browser
    defaults: { _controller: CoopTilleulsCKEditorSonataMediaBundle:MediaAdminController:browser }
    options:
        expose: true
cke_sonata_admin_upload:
    pattern: /admin/sonata/media/media/upload
    defaults: { _controller: CoopTilleulsCKEditorSonataMediaBundle:MediaAdminController:upload }
    options:
        expose: true

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    pattern: /login/check-facebook

oneup_uploader:
    resource: .
    type: uploader
