info_company:
  resource: "@InfoComplaintBundle/Resources/config/routing/company.yml"
  prefix:   /company

info_complaint_homepage:
    pattern:  /
    defaults:
        label: "Главная"
        _controller: InfoComplaintBundle:Default:home

info_complaint_create:
    pattern:  /complaint/create/{id}
    defaults:
        _controller: InfoComplaintBundle:Complaint:createComplaint
        id: null
        label: "Добавить отзыв"
        parent: info_complaint_homepage


info_complaint_category:
    pattern:  /companies/{categorySlug}
    defaults:
        _controller: InfoComplaintBundle:Category:showCategory
        categorySlug: null
        label: "Компании"
        parent: info_complaint_homepage

info_complaints_last:
    pattern:  /complaints/last/
    defaults: { _controller: InfoComplaintBundle:Complaint:lastAddedComplaints}

info_search:
    pattern:   /search/
    defaults:  { _controller: InfoComplaintBundle:Search:search, label: "Результаты поиска", parent: info_complaint_homepage }

search_auto:
    pattern:   /autocomplete/
    defaults:  { _controller: InfoComplaintBundle:Search:autoComplete }
    options:
        expose: true

info_manager:
    resource: "@InfoComplaintBundle/Resources/config/routing/manager.yml"
    prefix:   /

info_complaint_complaint:
    pattern:  /complaint/{id}
    defaults: { _controller: InfoComplaintBundle:Complaint:showComplaint}
    options:
        expose: true

info_complaint_edit:
    pattern: /complaint/edit/{complaint}/
    defaults:
        _controller: InfoComplaintBundle:Complaint:editComplaint
        label: "Редактировать отзыв"
        parent: info_complaint_homepage

info_complaint_delete:
    pattern: /complaint/delete/{complaint}/
    defaults: { _controller: InfoComplaintBundle:Complaint:deleteComplaint }

info_vote:
    pattern: /{type}/vote/{id}-{voteType}
    defaults: { _controller: InfoComplaintBundle:Complaint:vote}
    options:
        expose: true

upload_image:
    pattern: /upload/image/
    defaults: { _controller: InfoComplaintBundle:Default:upload}
    options:
        expose: true