info_complaint_homepage:
    pattern:  /
    defaults: { _controller: InfoComplaintBundle:Default:home }

info_complaint_create:
    pattern:  /create_complaint/
    defaults: { _controller: InfoComplaintBundle:Complaint:complaint }

info_complaint_list:
    pattern:  /allComplaint
    defaults: { _controller: InfoComplaintBundle:Complaint:allComplaint}

info_complaint_complaint:
    pattern:  /complaint/{id}
    defaults: { _controller: InfoComplaintBundle:Complaint:getComplaint}