info_complaint_homepage:
    pattern:  /hello/{name}/
    defaults: { _controller: InfoComplaintBundle:Default:index }

SearchEngineBundle_search:
    pattern:   /search/
    defaults:  { _controller: InfoComplaintBundle:Search:search }

SearchEngineBundle_results:
    pattern:   /results/
    defaults:  { _controller: InfoComplaintBundle:Search:getResults }

search_autocomplete:
    pattern:   /search_autocomplete/
    defaults:  { _controller: InfoComplaintBundle:Search:complete }

search_auto:
    pattern:   /autocomplete/
    defaults:  { _controller: InfoComplaintBundle:Search:autoComplete }
    options:
      expose: true