info_complaint_homepage:
    pattern:  /
    defaults: { _controller: InfoComplaintBundle:Default:home }

info_complaint_create:
    pattern:  /create_complaint/
    defaults: { _controller: InfoComplaintBundle:Complaint:complaint }
