# parameters:
#   info_complaint.company.class: Info\ComplaintBundle\Admin\CompanyAdmin

services:
  sonata.admin.company:
    class: Info\ComplaintBundle\Admin\CompanyAdmin
    tags: 
      - { name: sonata.admin, manager_type: orm, group: "Отзывы и предложения", label: "Компания"}
    arguments:
      - ~
      - Info\ComplaintBundle\Entity\Company
      - ~
    calls:
      - [ setTranslationDomain, [InfoComplaintBundle]]

  sonata.admin.complaint:
    class: Info\ComplaintBundle\Admin\ComplaintAdmin
    tags: 
      - { name: sonata.admin, manager_type: orm, group: "Отзывы и предложения", label: "Отзывы"}
    arguments:
      - ~
      - Info\ComplaintBundle\Entity\Complaint
      - ~
    calls:
      - [ setTranslationDomain, [InfoComplaintBundle]]


  complaint.menu.builder:
      class: Info\ComplaintBundle\Menu\MenuBuilder
      arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager"]

  strokit.menu.main:
      class: Knp\Menu\MenuItem # the service definition requires setting the class
      factory_service: complaint.menu.builder
      factory_method: createMainMenu
      arguments: ["@request"]
      scope: request # needed as we have the request as a dependency here
      tags:
          - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu


  strokit.menu.category_side_menu:
      class: Knp\Menu\MenuItem
      factory_service: complaint.menu.builder
      factory_method: createCategoryLeftMenu
      arguments:  [@request]
      scope: request
      tags:
          - { name: knp_menu.menu, alias: category_side_menu } # Named "sidebar" this time

  strokit.company_type:
    class: Info\ComplaintBundle\Form\CompanyType
    arguments: []
    tags:
      - { name: form.type, alias: company_type }

  sonata.admin.manager_request:
    class: Info\ComplaintBundle\Admin\ManagerRequestAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Отзывы и предложения", label: "Запросы на представительство"}
    arguments:
      - ~
      - Info\ComplaintBundle\Entity\ManagerRequest
      - InfoComplaintBundle:AdminManager
    calls:
      - [ setTranslationDomain, [InfoComplaintBundle]]
      
  my.controller.listener:
    class: Info\ComplaintBundle\Listener\VoteCookieResponseListener
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

  strokit.search:
      class: Info\ComplaintBundle\Twig\SearchExtension
      arguments: [@service_container]
      tags:
          - { name: twig.extension }
  strokit.vote:
      class: Info\ComplaintBundle\Twig\VoteExtension
      arguments: [@service_container, @doctrine.orm.entity_manager]
      tags:
          - { name: twig.extension }