# parameters:
#   info_complaint.company.class: Info\ComplaintBundle\Admin\CompanyAdmin

services:
  sonata.admin.company:
    class: Info\ComplaintBundle\Admin\CompanyAdmin
    tags: 
      - { name: sonata.admin, manager_type: orm, group: "Отзывы и предложения", label: "Компания"}
    arguments:
      - ~
      - Info\ComplaintBundle\Entity\Company
      - ~
    calls:
      - [ setTranslationDomain, [InfoComplaintBundle]]

  sonata.admin.complaint:
    class: Info\ComplaintBundle\Admin\ComplaintAdmin
    tags: 
      - { name: sonata.admin, manager_type: orm, group: "Отзывы и предложения", label: "Отзывы"}
    arguments:
      - ~
      - Info\ComplaintBundle\Entity\Complaint
      - ~
    calls:
      - [ setTranslationDomain, [InfoComplaintBundle]]


  complaint.menu.builder:
      class: Info\ComplaintBundle\Menu\MenuBuilder
      arguments: ["@knp_menu.factory","@doctrine.orm.entity_manager"]

  strokit.menu.category_side_menu:
      class: Knp\Menu\MenuItem
      factory_service: complaint.menu.builder
      factory_method: createCategoryLeftMenu
      arguments:  [@request]
      scope: request
      tags:
          - { name: knp_menu.menu, alias: category_side_menu } # Named "sidebar" this time

  strokit.company_type:
    class: Info\ComplaintBundle\Form\CompanyType
    arguments: []
    tags:
      - { name: form.type, alias: company_type }

  sonata.admin.manager_request:
    class: Info\ComplaintBundle\Admin\ManagerRequestAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Отзывы и предложения", label: "Запросы на представительство"}
    arguments:
      - ~
      - Info\ComplaintBundle\Entity\ManagerRequest
      - InfoComplaintBundle:AdminManager
    calls:
      - [ setTranslationDomain, [InfoComplaintBundle]]
      
  my.controller.listener:
    class: Info\ComplaintBundle\Listener\ControllerListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }           