# parameters:
#   info_complaint.company.class: Info\ComplaintBundle\Admin\CompanyAdmin

services:
  sonata.admin.company:
    class: Info\ComplaintBundle\Admin\CompanyAdmin
    tags: 
      - { name: sonata.admin, manager_type: orm, group: "Жалобы и предложения", label: "Компания"}
    arguments:
      - ~
      - Info\ComplaintBundle\Entity\Company
      - ~
    calls:
      - [ setTranslationDomain, [InfoComplaintBundle]]

  sonata.admin.complaint:
    class: Info\ComplaintBundle\Admin\ComplaintAdmin
    tags: 
      - { name: sonata.admin, manager_type: orm, group: "Жалобы и предложения", label: "Жалобы"}
    arguments:
      - ~
      - Info\ComplaintBundle\Entity\Complaint
      - ~
    calls:
      - [ setTranslationDomain, [InfoComplaintBundle]]