parameters:
  info_complaint.company.class: Info\ComplaintBundle\Admin\CompanyAdmin

services:
  sonata.admin.company:
    class: "%info_complaint.company.class%"
    tags: 
      - { name: sonata.admin, manager_type: orm, group: "Complaint", label: "Company"}
    arguments:
      - ~
      - Info\ComplaintBundle\Entity\Company
      - InfoComplaintBundle:CompanyAdmin
    calls:
      - [ setTranslationDomain, [InfoComplaintBundle]]