# parameters:
#   info_complaint.company.class: Info\ComplaintBundle\Admin\CompanyAdmin

services:
  sonata.admin.company:
    class: Info\ComplaintBundle\Admin\CompanyAdmin
    tags: 
      - { name: sonata.admin, manager_type: orm, group: "Отзывы и предложения", label: "Компания"}
    arguments:
      - ~
      - Info\ComplaintBundle\Entity\Company
      - ~
    calls:
      - [ setTranslationDomain, [InfoComplaintBundle]]

  sonata.admin.complaint:
    class: Info\ComplaintBundle\Admin\ComplaintAdmin
    tags: 
      - { name: sonata.admin, manager_type: orm, group: "Отзывы и предложения", label: "Отзывы"}
    arguments:
      - ~
      - Info\ComplaintBundle\Entity\Complaint
      - ~
    calls:
      - [ setTranslationDomain, [InfoComplaintBundle]]

  sonata.admin.manager_request:
    class: Info\ComplaintBundle\Admin\ManagerRequestAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Отзывы и предложения", label: "Запросы на представительство"}
    arguments:
      - ~
      - Info\ComplaintBundle\Entity\ManagerRequest
      - InfoComplaintBundle:AdminManager
    calls:
      - [ setTranslationDomain, [InfoComplaintBundle]]
      
    strokit.company_type:
        class: Info\ComplaintBundle\Form\CompanyType
        arguments: []
        tags:
            - { name: form.type, alias: company_type }
