parameters:
#    info_complaint.example.class: Info\ComplaintBundle\Example

services:
#    info_complaint.example:
#        class: %info_complaint.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
