<?php

namespace Info\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use FOS\UserBundle\Entity\User;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function markAsRead(User $user)
    {
        return $this->getEntityManager()->createQuery("
            UPDATE Info\NotificationBundle\Entity\Notification n set n.read = TRUE where n.user = :user
        ")->setParameter('user', $user->getId())
            ->execute();
    }

    public function countUnreadMessages($user)
    {
        return $this->getEntityManager()
            ->createQuery("select count(n) from Info\NotificationBundle\Entity\Notification n WHERE n.user = :user and n.read = FALSE")
            ->setParameter('user', $user)
            ->getSingleScalarResult();
    }

    public function findUserNotifications($user, $count = null)
    {
        return $this->findBy(array('user' => $user), array('id' => 'desc'), $count);
    }
}
