<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $facebookId
     */

    protected $resource;

    /**
     * @var boolean $emailOnNewComplaint
     */
    protected $emailOnNewComplaint = true;

    /**
     * @var boolean $emailOnNewComplaint
     */
    protected $emailOnNewComment = true;

    /**
     * @var boolean $emailOnNewComplaint
     */
    protected $emailOnReplyToComment = true;

    /**
     * @var boolean $notifyOnNewComplaint
     */
    protected $notifyOnNewComplaint = true;

    /**
     * @var boolean $notifyOnNewComplaint
     */
    protected $notifyOnNewComment = true;

    /**
     * @var boolean $notifyOnNewComplaint
     */
    protected $notifyOnReplyToComment = true;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return int
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * @param int $facebookId
     */
    public function setResource($facebookId)
    {
        $this->resource = $facebookId;
    }

    public function __toString()
    {
        return trim($this->getFullname())!=''? $this->getFullname():parent::__toString();
    }

    /**
     * @return boolean
     */
    public function getEmailOnNewComplaint()
    {
        return $this->emailOnNewComplaint;
    }

    /**
     * @param boolean $emailOnNewComplaint
     */
    public function setEmailOnNewComplaint($emailOnNewComplaint)
    {
        $this->emailOnNewComplaint = $emailOnNewComplaint;
    }

    /**
     * @return boolean
     */
    public function getEmailOnNewComment()
    {
        return $this->emailOnNewComment;
    }

    /**
     * @param boolean $emailOnNewComment
     */
    public function setEmailOnNewComment($emailOnNewComment)
    {
        $this->emailOnNewComment = $emailOnNewComment;
    }

    /**
     * @return boolean
     */
    public function getEmailOnReplyToComment()
    {
        return $this->emailOnReplyToComment;
    }

    /**
     * @param boolean $emailOnReplyToComment
     */
    public function setEmailOnReplyToComment($emailOnReplyToComment)
    {
        $this->emailOnReplyToComment = $emailOnReplyToComment;
    }

    /**
     * @return boolean
     */
    public function isNotifyOnNewComplaint()
    {
        return $this->notifyOnNewComplaint;
    }

    /**
     * @param boolean $notifyOnNewComplaint
     */
    public function setNotifyOnNewComplaint($notifyOnNewComplaint)
    {
        $this->notifyOnNewComplaint = $notifyOnNewComplaint;
    }

    /**
     * @return boolean
     */
    public function isNotifyOnNewComment()
    {
        return $this->notifyOnNewComment;
    }

    /**
     * @param boolean $notifyOnNewComment
     */
    public function setNotifyOnNewComment($notifyOnNewComment)
    {
        $this->notifyOnNewComment = $notifyOnNewComment;
    }

    /**
     * @return boolean
     */
    public function isNotifyOnReplyToComment()
    {
        return $this->notifyOnReplyToComment;
    }

    /**
     * @param boolean $notifyOnReplyToComment
     */
    public function setNotifyOnReplyToComment($notifyOnReplyToComment)
    {
        $this->notifyOnReplyToComment = $notifyOnReplyToComment;
    }

}