parameters:
#    nurix_page.example.class: Info\PageBundle\Example

services:
#    nurix_page.example:
#        class: %nurix_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    strokit.menu.info_sidebar:
            class: Knp\Menu\MenuItem
            factory_service: strokit.menu_builder
            factory_method: createBottomMenu
            arguments: ["@request"]
            scope: request
            tags:
                - { name: knp_menu.menu, alias: bottom } # Named "sidebar" this time

    sonata.admin.page:
            class: Info\PageBundle\Admin\PageAdmin
            tags:
              - { name: sonata.admin, manager_type: orm, group: "Сайт", label: "Страницы"}
            arguments:
              - ~
              - Info\PageBundle\Entity\Pages
              - ~