info_comment_create:
    pattern:  /comment/create/{complaint}/
    defaults: { _controller: InfoCommentBundle:Default:create }

info_comment_reply:
    pattern:  /comment/reply/{complaint}/{comment}/
    defaults: { _controller: InfoCommentBundle:Default:reply }
    options:
        expose: true