info_comment_create:
    pattern:  /comment/create/{complaint}/
    defaults: { _controller: InfoCommentBundle:Default:create }

info_comment_reply:
    pattern:  /comment/reply/{complaint}/{comment}/
    defaults: { _controller: InfoCommentBundle:Default:reply }
    options:
        expose: true

info_comment_edit:
    pattern: /comment/edit/{comment}/
    defaults: { _controller: InfoCommentBundle:Default:edit }
    methods: [POST]
    options:
        expose: true

info_comment_delete:
    pattern: /comment/delete/{comment}/
    defaults: { _controller: InfoCommentBundle:Default:delete }
    options:
        expose: true