parameters:
#    info_comment.example.class: Info\CommentBundle\Example

services:
#    info_comment.example:
#        class: %info_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sonata.admin.comment:
          class: Info\CommentBundle\Admin\CommentAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Отзывы и предложения", label: "Комментарии" }
          arguments:
              - ~
              - Info\CommentBundle\Entity\Comment
              - ~
          calls:
              - [ setTranslationDomain, [InfoCommentBundle]]

    strokit.comment_count:
        class: Info\CommentBundle\Twig\CommentCountExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }