parameters:
#    info_comment.example.class: Info\CommentBundle\Example

services:
#    info_comment.example:
#        class: %info_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
        sonata.admin.comment:
              class: Info\CommentBundle\Admin\CommentAdmin
              tags:
                  - { name: sonata.admin, manager_type: orm, group: "Жалобы и пожелания", label: "Комментарии" }
              arguments:
                  - ~
                  - Info\CommentBundle\Entity\Comment
                  - ~
              calls:
                  - [ setTranslationDomain, [InfoCommentBundle]]
