parameters:
#    info_comment.example.class: Info\CommentBundle\Example

services:
#    info_comment.example:
#        class: %info_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
