info_user_notification_edit:
    pattern: /profile/me/settings/notification
    defaults:
          _controller: ApplicationSonataUserBundle:Notification:emailNotificationSettings
          label: "Настройка уведомлений"
          parent: fos_user_profile_show

user_public_show:
    pattern: /user/{user}
    defaults:
          _controller: ApplicationSonataUserBundle:Public:show
          label: "{user_name}"
          parent: info_complaint_homepage