parameters:
  main_class_name: Application\Sonata\UserBundle\Model\OAuthUserProvider
  user_class_name: Application\Sonata\UserBundle\Entity\User
services:
    strokit.aouth_user_provider:
        class: %main_class_name%
        arguments:
            - @service_container
            - @doctrine
            - %user_class_name%

    strokit.twig.gravatar_image_ext:
        class: Application\Sonata\UserBundle\Twig\GravatarImageExtension
        tags:
            - { name: twig.extension }

    strokit.twig.user_ext:
        class: Application\Sonata\UserBundle\Twig\UserExtension
        arguments: [@security.context, @security.access.decision_manager]
        tags:
            - { name: twig.extension }

    sonata_user.registration.form.type:
            class: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
            tags:
                - { name: form.type, alias: sonata_user_registration }

    sonata.user.profile.form.type:
            class: Application\Sonata\UserBundle\Form\Type\ProfileType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: sonata_user_profile }

    sonata.user.success_authentication_handler:
        class:        Webibli\UserBundle\Handler\AuthenticationHandler
        arguments:    [@router, @security.context, @fos_user.user_manager, @service_container]